name: ht_categories_client
description: A Dart client interface for managing news categories. Defines the abstract client, models, and exceptions.
repository: https://github.com/headlines-toolkit/ht-categories-client
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  meta: ^1.16.0
  uuid: ^4.5.1
  
dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
